### ISSUE TITLE
Problem TerminalAPI and NewTerminal

### ISSUE THREAD

**Issue by DHStyle541** [EvaisaDev/LethalLib#18] opened 2023-12-24 08:53 UTC
Hi, I found a Bug/Error.
When I use TerminalAPI
then I spam "Scan in terminal" the game will bug (can't exit the terminal and Crash when exiting the game [ESC])

and when I Add "NewTerminal", an Error will appear too

![image](https://github.com/EvaisaDev/LethalLib/assets/154591650/fa259728-c6e8-4d64-a917-2a4ea70fe672)

**Comment by Hamunii** [comment] 2024-08-09 14:20
Sounds like this is a bug with TerminalAPI then? Closing this since this is old and doesn't have much info, and yeah, likely not caused by LethalLib.

**Closed as not planned by Hamunii** 2024-08-09 14:20 UTC
