### ISSUE TITLE
Cant see store items

### ISSUE THREAD

**Issue by Raboofoce** [EvaisaDev/LethalLib#63] opened 2024-02-24 23:18 UTC
When i am using termial to buy items - i just get the [fields with name of list](https://imgur.com/a/v99wcm1)
Soooo, the logs are below of what happens in that moment:
```
[Error  : Unity Log] An error occured while post processing terminal text: System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) Terminal.DMD<Terminal::TextPostProcess>(Terminal,string,TerminalNode)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<Terminal::TextPostProcess>?-725217712(Terminal,string,TerminalNode)
  at LethalLib.Modules.Items.Terminal_TextPostProcess (On.Terminal+orig_TextPostProcess orig, Terminal self, System.String modifiedDisplayText, TerminalNode node) [0x0004a] in <4eedb4dc36094adcb65137cf81f2803d>:IL_004A
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<Terminal::TextPostProcess>?1617163572(Terminal,string,TerminalNode)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<Terminal::TextPostProcess>?1468038060(Terminal,string,TerminalNode)
  at LethalLib.Modules.Unlockables.Terminal_TextPostProcess (On.Terminal+orig_TextPostProcess orig, Terminal self, System.String modifiedDisplayText, TerminalNode node) [0x000a0] in <4eedb4dc36094adcb65137cf81f2803d>:IL_00A0
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<Terminal::TextPostProcess>?1547251960(Terminal,string,TerminalNode)
  at (wrapper dynamic-method) Terminal.DMD<Terminal::LoadNewNode>(Terminal,TerminalNode)
```

Wonder if that happens cause of TerminalApi or something

**Comment by Hamunii** [comment] 2024-08-09 13:19
This is most likely not LethalLib causing this, at least directly. Possibly an incompatibility.

I'm gonna close this because LethalLib isn't known for breaking this, and this issue is kinda old by now (so it should probably be known by now if this was an issue caused by LethalLib).

**Closed as completed** 2024-08-09 14:08 UTC
